/**
 * The seed icon set.
 *
 * Every icon is drawn inside the 9x9 safe area (rows/cols 1–9), leaving the
 * symmetric 1-cell margin. Names, ids, and tags are kebab-case.
 *
 * SINGLE COLOR. The gallery renders every icon in one color, so every seed is
 * authored in one color too — multi-color cell data would be unreachable, and
 * would only surface as a surprise in an exported SVG.
 *
 * DRAWING NOTE: an icon must read as a silhouette. Draw OUTLINES, not filled
 * masses whose meaning depends on internal contrast — a filled envelope with a
 * lighter interior is a plain rectangle in one color; an outlined one survives.
 */

import type { IconDef } from "@/engine/types";
import { defineIcon } from "./authoring";

const SEEDED_AT = "2026-08-17T00:00:00.000Z";
const INK = { "#": "#111111" };

export const icons: readonly IconDef[] = [
  /* ---- interface ------------------------------------------------------- */

  defineIcon({
    id: "arrow-right",
    name: "arrow-right",
    category: "interface",
    tags: ["arrow", "right", "next", "forward", "direction"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      ".......#...",
      "........#..",
      ".#########.",
      "........#..",
      ".......#...",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "arrow-left",
    name: "arrow-left",
    category: "interface",
    tags: ["arrow", "left", "back", "previous", "direction"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "...#.......",
      "..#........",
      ".#########.",
      "..#........",
      "...#.......",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "check",
    name: "check",
    category: "interface",
    tags: ["check", "done", "ok", "tick", "confirm"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".........#.",
      "........##.",
      ".......##..",
      ".#...##....",
      ".##.##.....",
      "..###......",
      "...#.......",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "close",
    name: "close",
    category: "interface",
    tags: ["close", "cancel", "cross", "dismiss", "remove"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".#.......#.",
      ".##.....##.",
      "..##...##..",
      "...##.##...",
      "....###....",
      "...##.##...",
      "..##...##..",
      ".##.....##.",
      ".#.......#.",
      "...........",
    ],
  }),

  defineIcon({
    id: "plus",
    name: "plus",
    category: "interface",
    tags: ["plus", "add", "new", "create", "more"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "....###....",
      "....###....",
      ".#########.",
      ".#########.",
      ".#########.",
      "....###....",
      "....###....",
      "....###....",
      "...........",
    ],
  }),

  defineIcon({
    id: "menu",
    name: "menu",
    category: "interface",
    tags: ["menu", "list", "hamburger", "nav", "lines"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      "...........",
      "...........",
      ".#########.",
      "...........",
      "...........",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "search",
    name: "search",
    category: "interface",
    tags: ["search", "find", "magnifier", "zoom", "look"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "..####.....",
      ".#....#....",
      ".#....#....",
      ".#....#....",
      "..####.....",
      "....##.....",
      ".....##....",
      "......##...",
      ".......#...",
      "...........",
    ],
  }),

  /* ---- media ----------------------------------------------------------- */

  defineIcon({
    id: "play",
    name: "play",
    category: "media",
    tags: ["play", "start", "media", "video", "triangle"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...#.......",
      "...##......",
      "...###.....",
      "...####....",
      "...#####...",
      "...####....",
      "...###.....",
      "...##......",
      "...#.......",
      "...........",
    ],
  }),

  defineIcon({
    id: "pause",
    name: "pause",
    category: "media",
    tags: ["pause", "stop", "media", "halt", "break"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "volume",
    name: "volume",
    category: "media",
    tags: ["volume", "sound", "audio", "speaker", "loud"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "......#....",
      ".....##.#..",
      "..######.#.",
      "..######.#.",
      "..######.#.",
      ".....##.#..",
      "......#....",
      "...........",
      "...........",
    ],
  }),

  /* ---- arcade ---------------------------------------------------------- */

  defineIcon({
    id: "heart",
    name: "heart",
    category: "arcade",
    tags: ["heart", "life", "health", "love", "favorite"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "..##...##..",
      ".#########.",
      ".#########.",
      ".#########.",
      ".#########.",
      "..#######..",
      "...#####...",
      "....###....",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "coin",
    name: "coin",
    category: "arcade",
    tags: ["coin", "credit", "token", "money", "score"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##.....##.",
      ".#.......#.",
      ".#..###..#.",
      ".#..#.#..#.",
      ".#..###..#.",
      ".#.......#.",
      ".##.....##.",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "ghost",
    name: "ghost",
    category: "arcade",
    tags: ["ghost", "enemy", "spooky", "arcade", "maze"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      "..#.....#..",
      ".#..#.#..#.",
      ".#..#.#..#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.#.#.#.#.",
      "...........",
    ],
  }),

  defineIcon({
    id: "trophy",
    name: "trophy",
    category: "arcade",
    tags: ["trophy", "win", "award", "prize", "high-score"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      "..#######..",
      "....###....",
      ".....#.....",
      ".....#.....",
      "...#####...",
      "..#######..",
      "...........",
    ],
  }),

  /* ---- system ---------------------------------------------------------- */

  defineIcon({
    id: "floppy-disk",
    name: "floppy-disk",
    category: "system",
    tags: ["floppy", "disk", "save", "storage", "file"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#..###..#.",
      ".#..#.#..#.",
      ".#..###..#.",
      ".#.......#.",
      ".#.#####.#.",
      ".#.#...#.#.",
      ".#.#####.#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "folder",
    name: "folder",
    category: "system",
    tags: ["folder", "directory", "files", "storage", "open"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "..####.....",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "battery",
    name: "battery",
    category: "system",
    tags: ["battery", "power", "charge", "energy", "level"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#######...",
      ".#.....#...",
      ".#.###.#...",
      ".#.###.###.",
      ".#.###.#...",
      ".#.....#...",
      ".#######...",
      "...........",
      "...........",
    ],
  }),

  /* ---- communication --------------------------------------------------- */

  defineIcon({
    id: "mail",
    name: "mail",
    category: "communication",
    tags: ["mail", "email", "envelope", "message", "inbox"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      ".##.....##.",
      ".#.##.##.#.",
      ".#..###..#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "chat",
    name: "chat",
    category: "communication",
    tags: ["chat", "message", "bubble", "talk", "comment"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      "...##......",
      "..##.......",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "bell",
    name: "bell",
    category: "communication",
    tags: ["bell", "notification", "alert", "ring", "reminder"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "....#.#....",
      "...#...#...",
      "...#...#...",
      "..#.....#..",
      "..#.....#..",
      ".#########.",
      "....###....",
      ".....#.....",
      "...........",
    ],
  }),

  /* ---- nature ---------------------------------------------------------- */

  defineIcon({
    id: "sun",
    name: "sun",
    category: "nature",
    tags: ["sun", "weather", "light", "day", "bright"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "..#.....#..",
      "....###....",
      "...#####...",
      ".#.#####.#.",
      "...#####...",
      "....###....",
      "..#.....#..",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "moon",
    name: "moon",
    category: "nature",
    tags: ["moon", "night", "crescent", "dark", "sleep"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "...#...#...",
      "..#...##...",
      "..#..##....",
      "..#..#.....",
      "..#..##....",
      "..#...##...",
      "...#...#...",
      "....###....",
      "...........",
    ],
  }),

  defineIcon({
    id: "star",
    name: "star",
    category: "nature",
    tags: ["star", "favorite", "rating", "night", "sparkle"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "....###....",
      "....###....",
      ".#########.",
      ".#########.",
      "..#######..",
      "...#####...",
      "..##.#.##..",
      ".##.....##.",
      "...........",
    ],
  }),

  defineIcon({
    id: "cloud",
    name: "cloud",
    category: "nature",
    tags: ["cloud", "weather", "sky", "overcast", "storage"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "....###....",
      "...######..",
      ".#########.",
      ".#########.",
      "..#######..",
      "...........",
      "...........",
      "...........",
    ],
  }),
];

/** Look up one icon by its stable id. */
export function getIcon(id: string): IconDef | undefined {
  return icons.find((icon) => icon.id === id);
}
